//	stationaryorbit.core:/arithmetic
//	Copyright 2020-2021 zawa-ch.
//	GPLv3 (or later) license
//
//	This program is free software: you can redistribute it and/or modify
//	it under the terms of the GNU General Public License as published by
//	the Free Software Foundation, either version 3 of the License, or
//	any later version.
//
//	This program is distributed in the hope that it will be useful,
//	but WITHOUT ANY WARRANTY; without even the implied warranty of
//	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//	See the GNU General Public License for more details.
//
//	You should have received a copy of the GNU General Public License
//	along with this program.
//	If not, see <http://www.gnu.org/licenses/>.
//
#include "stationaryorbit/core/arithmetic.hpp"
using namespace zawa_ch::StationaryOrbit;

template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<bool> zawa_ch::StationaryOrbit::ArithmeticOperation::add<bool>(const bool&, const bool&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<char> zawa_ch::StationaryOrbit::ArithmeticOperation::add<char>(const char&, const char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<signed char> zawa_ch::StationaryOrbit::ArithmeticOperation::add<signed char>(const signed char&, const signed char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned char> zawa_ch::StationaryOrbit::ArithmeticOperation::add<unsigned char>(const unsigned char&, const unsigned char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<wchar_t> zawa_ch::StationaryOrbit::ArithmeticOperation::add<wchar_t>(const wchar_t&, const wchar_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<short> zawa_ch::StationaryOrbit::ArithmeticOperation::add<short>(const short&, const short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned short> zawa_ch::StationaryOrbit::ArithmeticOperation::add<unsigned short>(const unsigned short&, const unsigned short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<int> zawa_ch::StationaryOrbit::ArithmeticOperation::add<int>(const int&, const int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned int> zawa_ch::StationaryOrbit::ArithmeticOperation::add<unsigned int>(const unsigned int&, const unsigned int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<long> zawa_ch::StationaryOrbit::ArithmeticOperation::add<long>(const long&, const long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned long> zawa_ch::StationaryOrbit::ArithmeticOperation::add<unsigned long>(const unsigned long&, const unsigned long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<long long> zawa_ch::StationaryOrbit::ArithmeticOperation::add<long long>(const long long&, const long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned long long> zawa_ch::StationaryOrbit::ArithmeticOperation::add<unsigned long long>(const unsigned long long&, const unsigned long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<float> zawa_ch::StationaryOrbit::ArithmeticOperation::add<float>(const float&, const float&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<double> zawa_ch::StationaryOrbit::ArithmeticOperation::add<double>(const double&, const double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<long double> zawa_ch::StationaryOrbit::ArithmeticOperation::add<long double>(const long double&, const long double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<char16_t> zawa_ch::StationaryOrbit::ArithmeticOperation::add<char16_t>(const char16_t&, const char16_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<char32_t> zawa_ch::StationaryOrbit::ArithmeticOperation::add<char32_t>(const char32_t&, const char32_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<bool> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<bool>(const bool&, const bool&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<char> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<char>(const char&, const char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<signed char> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<signed char>(const signed char&, const signed char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned char> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<unsigned char>(const unsigned char&, const unsigned char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<wchar_t> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<wchar_t>(const wchar_t&, const wchar_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<short> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<short>(const short&, const short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned short> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<unsigned short>(const unsigned short&, const unsigned short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<int> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<int>(const int&, const int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned int> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<unsigned int>(const unsigned int&, const unsigned int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<long> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<long>(const long&, const long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned long> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<unsigned long>(const unsigned long&, const unsigned long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<long long> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<long long>(const long long&, const long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned long long> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<unsigned long long>(const unsigned long long&, const unsigned long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<float> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<float>(const float&, const float&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<double> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<double>(const double&, const double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<long double> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<long double>(const long double&, const long double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<char16_t> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<char16_t>(const char16_t&, const char16_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<char32_t> zawa_ch::StationaryOrbit::ArithmeticOperation::subtract<char32_t>(const char32_t&, const char32_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<bool> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<bool>(const bool&, const bool&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<char> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<char>(const char&, const char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<signed char> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<signed char>(const signed char&, const signed char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned char> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<unsigned char>(const unsigned char&, const unsigned char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<wchar_t> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<wchar_t>(const wchar_t&, const wchar_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<short> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<short>(const short&, const short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned short> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<unsigned short>(const unsigned short&, const unsigned short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<int> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<int>(const int&, const int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned int> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<unsigned int>(const unsigned int&, const unsigned int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<long> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<long>(const long&, const long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned long> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<unsigned long>(const unsigned long&, const unsigned long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<long long> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<long long>(const long long&, const long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned long long> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<unsigned long long>(const unsigned long long&, const unsigned long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<float> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<float>(const float&, const float&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<double> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<double>(const double&, const double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<long double> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<long double>(const long double&, const long double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<char16_t> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<char16_t>(const char16_t&, const char16_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<char32_t> zawa_ch::StationaryOrbit::ArithmeticOperation::multiply<char32_t>(const char32_t&, const char32_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<bool> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<bool>(const bool&, const bool&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<char> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<char>(const char&, const char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<signed char> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<signed char>(const signed char&, const signed char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned char> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<unsigned char>(const unsigned char&, const unsigned char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<wchar_t> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<wchar_t>(const wchar_t&, const wchar_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<short> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<short>(const short&, const short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned short> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<unsigned short>(const unsigned short&, const unsigned short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<int> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<int>(const int&, const int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned int> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<unsigned int>(const unsigned int&, const unsigned int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<long> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<long>(const long&, const long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned long> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<unsigned long>(const unsigned long&, const unsigned long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<long long> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<long long>(const long long&, const long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned long long> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<unsigned long long>(const unsigned long long&, const unsigned long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<float> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<float>(const float&, const float&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<double> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<double>(const double&, const double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<long double> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<long double>(const long double&, const long double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<char16_t> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<char16_t>(const char16_t&, const char16_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<char32_t> zawa_ch::StationaryOrbit::ArithmeticOperation::divide<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::add_saturate<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_saturate<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_saturate<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::divide_saturate<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::add_checked<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::subtract_checked<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::multiply_checked<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::divide_checked<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<bool>(const bool&, const bool&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<char>(const char&, const char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<signed char>(const signed char&, const signed char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<unsigned char>(const unsigned char&, const unsigned char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<wchar_t>(const wchar_t&, const wchar_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<short>(const short&, const short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<unsigned short>(const unsigned short&, const unsigned short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<int>(const int&, const int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<unsigned int>(const unsigned int&, const unsigned int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<long>(const long&, const long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<unsigned long>(const unsigned long&, const unsigned long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<long long>(const long long&, const long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<unsigned long long>(const unsigned long long&, const unsigned long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<float>(const float&, const float&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<double>(const double&, const double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<long double>(const long double&, const long double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<char16_t>(const char16_t&, const char16_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_addition<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<bool>(const bool&, const bool&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<char>(const char&, const char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<signed char>(const signed char&, const signed char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<unsigned char>(const unsigned char&, const unsigned char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<wchar_t>(const wchar_t&, const wchar_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<short>(const short&, const short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<unsigned short>(const unsigned short&, const unsigned short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<int>(const int&, const int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<unsigned int>(const unsigned int&, const unsigned int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<long>(const long&, const long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<unsigned long>(const unsigned long&, const unsigned long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<long long>(const long long&, const long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<unsigned long long>(const unsigned long long&, const unsigned long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<float>(const float&, const float&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<double>(const double&, const double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<long double>(const long double&, const long double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<char16_t>(const char16_t&, const char16_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_subtraction<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<bool>(const bool&, const bool&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<char>(const char&, const char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<signed char>(const signed char&, const signed char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<unsigned char>(const unsigned char&, const unsigned char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<wchar_t>(const wchar_t&, const wchar_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<short>(const short&, const short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<unsigned short>(const unsigned short&, const unsigned short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<int>(const int&, const int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<unsigned int>(const unsigned int&, const unsigned int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<long>(const long&, const long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<unsigned long>(const unsigned long&, const unsigned long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<long long>(const long long&, const long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<unsigned long long>(const unsigned long long&, const unsigned long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<float>(const float&, const float&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<double>(const double&, const double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<long double>(const long double&, const long double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<char16_t>(const char16_t&, const char16_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_multiplication<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<bool>(const bool&, const bool&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<char>(const char&, const char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<signed char>(const signed char&, const signed char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<unsigned char>(const unsigned char&, const unsigned char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<wchar_t>(const wchar_t&, const wchar_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<short>(const short&, const short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<unsigned short>(const unsigned short&, const unsigned short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<int>(const int&, const int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<unsigned int>(const unsigned int&, const unsigned int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<long>(const long&, const long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<unsigned long>(const unsigned long&, const unsigned long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<long long>(const long long&, const long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<unsigned long long>(const unsigned long long&, const unsigned long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<float>(const float&, const float&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<double>(const double&, const double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<long double>(const long double&, const long double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<char16_t>(const char16_t&, const char16_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::may_overflow_division<char32_t>(const char32_t&, const char32_t&);
