//	stationaryorbit.core:/arithmetic
//	Copyright 2020 zawa-ch.
//	GPLv3 (or later) license
//
//	This program is free software: you can redistribute it and/or modify
//	it under the terms of the GNU General Public License as published by
//	the Free Software Foundation, either version 3 of the License, or
//	any later version.
//
//	This program is distributed in the hope that it will be useful,
//	but WITHOUT ANY WARRANTY; without even the implied warranty of
//	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//	See the GNU General Public License for more details.
//
//	You should have received a copy of the GNU General Public License
//	along with this program.
//	If not, see <http://www.gnu.org/licenses/>.
//
#include "stationaryorbit/core/arithmetic.hpp"
using namespace zawa_ch::StationaryOrbit;

template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<bool> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<bool>(const bool&, const bool&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<char> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<char>(const char&, const char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<signed char> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<signed char>(const signed char&, const signed char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned char> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<unsigned char>(const unsigned char&, const unsigned char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<wchar_t> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<wchar_t>(const wchar_t&, const wchar_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<short> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<short>(const short&, const short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned short> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<unsigned short>(const unsigned short&, const unsigned short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<int> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<int>(const int&, const int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned int> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<unsigned int>(const unsigned int&, const unsigned int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<long> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<long>(const long&, const long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned long> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<unsigned long>(const unsigned long&, const unsigned long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<long long> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<long long>(const long long&, const long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned long long> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<unsigned long long>(const unsigned long long&, const unsigned long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<float> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<float>(const float&, const float&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<double> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<double>(const double&, const double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<long double> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<long double>(const long double&, const long double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<char16_t> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<char16_t>(const char16_t&, const char16_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<char32_t> zawa_ch::StationaryOrbit::ArithmeticOperation::Add<char32_t>(const char32_t&, const char32_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<bool> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<bool>(const bool&, const bool&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<char> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<char>(const char&, const char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<signed char> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<signed char>(const signed char&, const signed char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned char> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<unsigned char>(const unsigned char&, const unsigned char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<wchar_t> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<wchar_t>(const wchar_t&, const wchar_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<short> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<short>(const short&, const short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned short> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<unsigned short>(const unsigned short&, const unsigned short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<int> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<int>(const int&, const int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned int> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<unsigned int>(const unsigned int&, const unsigned int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<long> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<long>(const long&, const long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned long> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<unsigned long>(const unsigned long&, const unsigned long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<long long> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<long long>(const long long&, const long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<unsigned long long> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<unsigned long long>(const unsigned long long&, const unsigned long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<float> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<float>(const float&, const float&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<double> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<double>(const double&, const double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<long double> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<long double>(const long double&, const long double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<char16_t> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<char16_t>(const char16_t&, const char16_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::AdditionResult<char32_t> zawa_ch::StationaryOrbit::ArithmeticOperation::Subtract<char32_t>(const char32_t&, const char32_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<bool> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<bool>(const bool&, const bool&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<char> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<char>(const char&, const char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<signed char> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<signed char>(const signed char&, const signed char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned char> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<unsigned char>(const unsigned char&, const unsigned char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<wchar_t> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<wchar_t>(const wchar_t&, const wchar_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<short> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<short>(const short&, const short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned short> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<unsigned short>(const unsigned short&, const unsigned short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<int> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<int>(const int&, const int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned int> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<unsigned int>(const unsigned int&, const unsigned int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<long> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<long>(const long&, const long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned long> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<unsigned long>(const unsigned long&, const unsigned long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<long long> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<long long>(const long long&, const long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned long long> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<unsigned long long>(const unsigned long long&, const unsigned long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<float> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<float>(const float&, const float&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<double> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<double>(const double&, const double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<long double> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<long double>(const long double&, const long double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<char16_t> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<char16_t>(const char16_t&, const char16_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<char32_t> zawa_ch::StationaryOrbit::ArithmeticOperation::Multiply<char32_t>(const char32_t&, const char32_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<bool> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<bool>(const bool&, const bool&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<char> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<char>(const char&, const char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<signed char> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<signed char>(const signed char&, const signed char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned char> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<unsigned char>(const unsigned char&, const unsigned char&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<wchar_t> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<wchar_t>(const wchar_t&, const wchar_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<short> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<short>(const short&, const short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned short> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<unsigned short>(const unsigned short&, const unsigned short&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<int> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<int>(const int&, const int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned int> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<unsigned int>(const unsigned int&, const unsigned int&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<long> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<long>(const long&, const long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned long> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<unsigned long>(const unsigned long&, const unsigned long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<long long> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<long long>(const long long&, const long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<unsigned long long> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<unsigned long long>(const unsigned long long&, const unsigned long long&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<float> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<float>(const float&, const float&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<double> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<double>(const double&, const double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<long double> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<long double>(const long double&, const long double&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<char16_t> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<char16_t>(const char16_t&, const char16_t&);
template zawa_ch::StationaryOrbit::ArithmeticOperation::MultiplicationResult<char32_t> zawa_ch::StationaryOrbit::ArithmeticOperation::Divide<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateAdd<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateSubtract<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateMultiply<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::SaturateDivide<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedAdd<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedSubtract<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedMultiply<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<bool>(const bool&, const bool&);
template char zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<char>(const char&, const char&);
template signed char zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<signed char>(const signed char&, const signed char&);
template unsigned char zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<unsigned char>(const unsigned char&, const unsigned char&);
template wchar_t zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<wchar_t>(const wchar_t&, const wchar_t&);
template short zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<short>(const short&, const short&);
template unsigned short zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<unsigned short>(const unsigned short&, const unsigned short&);
template int zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<int>(const int&, const int&);
template unsigned int zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<unsigned int>(const unsigned int&, const unsigned int&);
template long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<long>(const long&, const long&);
template unsigned long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<unsigned long>(const unsigned long&, const unsigned long&);
template long long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<long long>(const long long&, const long long&);
template unsigned long long zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<unsigned long long>(const unsigned long long&, const unsigned long long&);
template float zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<float>(const float&, const float&);
template double zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<double>(const double&, const double&);
template long double zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<long double>(const long double&, const long double&);
template char16_t zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<char16_t>(const char16_t&, const char16_t&);
template char32_t zawa_ch::StationaryOrbit::ArithmeticOperation::CheckedDivide<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<bool>(const bool&, const bool&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<char>(const char&, const char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<signed char>(const signed char&, const signed char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<unsigned char>(const unsigned char&, const unsigned char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<wchar_t>(const wchar_t&, const wchar_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<short>(const short&, const short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<unsigned short>(const unsigned short&, const unsigned short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<int>(const int&, const int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<unsigned int>(const unsigned int&, const unsigned int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<long>(const long&, const long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<unsigned long>(const unsigned long&, const unsigned long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<long long>(const long long&, const long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<unsigned long long>(const unsigned long long&, const unsigned long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<float>(const float&, const float&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<double>(const double&, const double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<long double>(const long double&, const long double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<char16_t>(const char16_t&, const char16_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithAddition<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<bool>(const bool&, const bool&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<char>(const char&, const char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<signed char>(const signed char&, const signed char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<unsigned char>(const unsigned char&, const unsigned char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<wchar_t>(const wchar_t&, const wchar_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<short>(const short&, const short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<unsigned short>(const unsigned short&, const unsigned short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<int>(const int&, const int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<unsigned int>(const unsigned int&, const unsigned int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<long>(const long&, const long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<unsigned long>(const unsigned long&, const unsigned long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<long long>(const long long&, const long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<unsigned long long>(const unsigned long long&, const unsigned long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<float>(const float&, const float&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<double>(const double&, const double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<long double>(const long double&, const long double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<char16_t>(const char16_t&, const char16_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithSubtraction<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<bool>(const bool&, const bool&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<char>(const char&, const char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<signed char>(const signed char&, const signed char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<unsigned char>(const unsigned char&, const unsigned char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<wchar_t>(const wchar_t&, const wchar_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<short>(const short&, const short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<unsigned short>(const unsigned short&, const unsigned short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<int>(const int&, const int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<unsigned int>(const unsigned int&, const unsigned int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<long>(const long&, const long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<unsigned long>(const unsigned long&, const unsigned long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<long long>(const long long&, const long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<unsigned long long>(const unsigned long long&, const unsigned long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<float>(const float&, const float&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<double>(const double&, const double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<long double>(const long double&, const long double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<char16_t>(const char16_t&, const char16_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithMultiplication<char32_t>(const char32_t&, const char32_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<bool>(const bool&, const bool&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<char>(const char&, const char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<signed char>(const signed char&, const signed char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<unsigned char>(const unsigned char&, const unsigned char&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<wchar_t>(const wchar_t&, const wchar_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<short>(const short&, const short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<unsigned short>(const unsigned short&, const unsigned short&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<int>(const int&, const int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<unsigned int>(const unsigned int&, const unsigned int&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<long>(const long&, const long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<unsigned long>(const unsigned long&, const unsigned long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<long long>(const long long&, const long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<unsigned long long>(const unsigned long long&, const unsigned long long&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<float>(const float&, const float&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<double>(const double&, const double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<long double>(const long double&, const long double&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<char16_t>(const char16_t&, const char16_t&);
template bool zawa_ch::StationaryOrbit::ArithmeticOperation::MayOverflowWithDivision<char32_t>(const char32_t&, const char32_t&);
